version: "3.7"
services:
  config-server:
    container_name: config-server
    build: ./config-server
    image: neoflex-config-server
    networks:
      - neoflex-network

  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    image: neoflex-eureka-server
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER_URL: optional:configserver:http://config-server:8888
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    depends_on:
      - config-server
    networks:
      - neoflex-network

  gateway:
    container_name: gateway
    build: ./gateway
    image: neoflex-gateway
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_URL: optional:configserver:http://config-server:8888
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: gateway
    depends_on:
      - config-server
    networks:
      - neoflex-network

  vacation-pay-calculator:
    container_name: calculator
    build: ./vacation-pay-calculator
    image: neoflex-vacation-pay-calculator
    environment:
      CONFIG_SERVER_URL: optional:configserver:http://config-server:8888
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: vacation-pay-calculator
    depends_on:
      - config-server
    networks:
      - neoflex-network

networks:
  neoflex-network:
    driver: bridge
