version: "3.7"
services:
  config-server:
    container_name: config-server
    build: ./config-server
    image: neoflex-config-server
    healthcheck:
      test: ["CMD", "curl", "-I", "http://config-server:8888"]
      start_interval: 30s
      interval: 5s
      retries: 10
    networks:
      - neoflex-network

  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    image: neoflex-eureka-server
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER_URL: optional:configserver:http://config-server:8888
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://eureka-server:8761" ]
      start_interval: 30s
      interval: 5s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
        restart: true
    networks:
      - neoflex-network

  gateway:
    container_name: gateway
    build: ./gateway
    image: neoflex-gateway
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_URL: optional:configserver:http://config-server:8888
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: gateway
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://gateway:8080" ]
      start_interval: 30s
      interval: 5s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
        restart: true
      eureka-server:
        condition: service_healthy
        restart: true
    networks:
      - neoflex-network

  vacation-pay-calculator:
    container_name: calculator
    build: ./vacation-pay-calculator
    image: neoflex-vacation-pay-calculator
    environment:
      CONFIG_SERVER_URL: optional:configserver:http://config-server:8888
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: vacation-pay-calculator
    depends_on:
      config-server:
        condition: service_healthy
        restart: true
      gateway:
        condition: service_healthy
    networks:
      - neoflex-network

networks:
  neoflex-network:
    driver: bridge
