# Use a Java base image
FROM openjdk:17-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the Spring Boot application JAR file into the Docker image
COPY target/config-server-0.0.1-SNAPSHOT.jar /app/config-server.jar

# EXPOSE 8888

# Run the Spring Boot application when the container starts
CMD ["java", "-jar", "config-server.jar"]