server:
  port: 0
spring:
  application:
    name: vacation-pay-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  calculate:
    ndflRate: "0.13"
    averageNumOfDaysInMonth: "29.3"
